---
title: Khanh Hoang.
email: ''
description: I'm a senior Computer Engineering student studying at Cal Poly currently
  looking for a Software Engineering position. I have an interest in embedded, networks,
  security development.
baseurl: ''
url: https://kkhanhh.github.io
github_username: kkhanhh
linkedin_username: khanh-hoang-352b10117
markdown: kramdown
theme: phantom
theme_text: Theme used is Phantom
theme_url: https://github.com/jamigibbs/phantom
plugins:
- jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: "10"
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: "0"
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: "2"
    after: "2"
  extension: html
  indexpage: index
footer_text: "© 2022 Khanh Hoang"
admin_name: Khanh Hoang
profile_pic: "/uploads/KhanhProfile.png"
google_analytics: G-5EKTESEZK0
enable_contact: true
enable_nav: true
nav_item:
- url: "/"
  text: Home
- url: "/projects"
  text: Projects
